apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: course-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
      - name: course-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: APP_STORE
          value: "redis"
        - name: APP_REDIS_URL
          value: "redis://{{ .Values.redis.host }}:6379"
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: course-app-config
              key: APP_COLOR
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
